import matplotlib.pyplot as plt


x1 = []
y1 = []


def f_2(x,a,b,c):
    return a*(x**2)+b*x+c


def a(x,a,b,c):
    x1.append(x)
    x1.append(x+0.2)
    x1.append(x+0.4)
    x1.append(x+0.6)
    x1.append(x+0.8)
    x1.append(x+1)
    x1.append(x+1.2)
    x1.append(x+1.4)
    x1.append(x+1.6)
    x1.append(x+1.8)
    x1.append(x+2)
    x1.append(x+2.2)
    x1.append(x+2.4)
    x1.append(x+2.6)
    x1.append(x+2.8)
    x1.append(x+3)
    x1.append(x-0.2)
    x1.append(x-0.4)
    x1.append(x-0.6)
    x1.append(x-0.8)
    x1.append(x-1)
    x1.append(x-1.2)
    x1.append(x-1.4)
    x1.append(x-1.6)
    x1.append(x-1.8)
    x1.append(x-2)
    x1.append(x-2.2)
    x1.append(x-2.4)
    x1.append(x-2.6)
    x1.append(x-2.8)
    x1.append(x-3)
        
    ya = f_2(x,a,b,c)
    y1.append(ya)
    yi = f_2(x+0.2,a,b,c)
    y1.append(yi)
    yj = f_2(x+0.4,a,b,c)
    y1.append(yj)
    yk = f_2(x+0.6,a,b,c)
    y1.append(yk)
    yl = f_2(x+0.8,a,b,c)
    y1.append(yl)
    yb = f_2(x+1,a,b,c)
    y1.append(yb)
    yh = f_2(x+1.2,a,b,c)
    y1.append(yh)
    ym = f_2(x+1.4,a,b,c)
    y1.append(ym)
    yn = f_2(x+1.6,a,b,c)
    y1.append(yn)
    yo = f_2(x+1.8,a,b,c)
    y1.append(yo)
    yc = f_2(x+2,a,b,c)
    y1.append(yc)
    yp = f_2(x+2.2,a,b,c)
    y1.append(yp)
    yq = f_2(x+2.4,a,b,c)
    y1.append(yq)
    yr = f_2(x+2.6,a,b,c)
    y1.append(yr)
    ys = f_2(x+2.8,a,b,c)
    y1.append(ys)
    yf = f_2(x+3,a,b,c)
    y1.append(yf)
    yd = f_2(x-0.2,a,b,c)
    y1.append(yd)
    yd = f_2(x-0.4,a,b,c)
    y1.append(yd)
    yd = f_2(x-0.6,a,b,c)
    y1.append(yd)
    yd = f_2(x-0.8,a,b,c)
    y1.append(yd)
    yd = f_2(x-1,a,b,c)
    y1.append(yd)
    yd = f_2(x-1.2,a,b,c)
    y1.append(yd)
    yd = f_2(x-1.4,a,b,c)
    y1.append(yd)
    yd = f_2(x-1.6,a,b,c)
    y1.append(yd)
    yd = f_2(x-1.8,a,b,c)
    y1.append(yd)
    ye = f_2(x-2,a,b,c)
    y1.append(ye)
    ye = f_2(x-2.2,a,b,c)
    y1.append(ye)
    ye = f_2(x-2.4,a,b,c)
    y1.append(ye)
    ye = f_2(x-2.6,a,b,c)
    y1.append(ye)
    ye = f_2(x-2.8,a,b,c)
    y1.append(ye)
    yg = f_2(x-3,a,b,c)
    y1.append(yg)
        
    plt.scatter(x1,y1,s=10,c='b')
    plt.xlabel('x')
    plt.ylabel('y')
    
    plt.grid()    
    plt.show()
    plt.close()


